package com.aitip.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * JPA Entity mapped to the {@code users} table.
 *
 * <p><b>Purpose:</b> Represents a registered user in the database.
 * This class is the persistence boundary — it is NEVER returned
 * directly to API consumers. Always map to a DTO first.</p>
 *
 * <p><b>Why Lombok here but Records for DTOs?</b>
 * <ul>
 *   <li>Entities need mutable state (JPA proxies, setters for updates)</li>
 *   <li>Entities require a no-arg constructor for Hibernate</li>
 *   <li>DTOs are immutable data carriers — perfect for Records</li>
 * </ul></p>
 *
 * <p><b>Why @Builder?</b>
 * Clean, readable object construction in service layer.
 * Avoids telescoping constructors.</p>
 */
@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    /**
     * WHY UUID?
     * - Prevents sequential enumeration attacks
     * - Safe for distributed / multi-region deployments
     * - Generated by PostgreSQL (gen_random_uuid)
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @Column(name = "name", nullable = false, length = 100)
    private String name;

    /**
     * Email is the unique login identifier.
     * Uniqueness enforced at both DB level (constraint) and
     * application level (service validation).
     */
    @Column(name = "email", nullable = false, unique = true, length = 255)
    private String email;

    /**
     * Stores BCrypt-hashed password.
     * NEVER included in any response DTO.
     */
    @Column(name = "password", nullable = false, length = 255)
    private String password;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * WHY @PrePersist / @PreUpdate?
     * Defense-in-depth: sets timestamps at application level.
     * The database trigger also sets updated_at, but we don't
     * rely solely on DB-side logic.
     */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}
