CREATE TABLE recommendation_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id),
    recommendation_type VARCHAR(100) NOT NULL,
    currency VARCHAR(3),
    action VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    snoozed_until TIMESTAMP
);

CREATE INDEX idx_recommendation_actions_user_type_currency 
ON recommendation_actions (user_id, recommendation_type, currency);
